### PR TITLE
Robust support for UTF-8 Fixtures and Housekeeping

### PR DESCRIPTION
**Pull request by iliakur**
Based on investigating #6. In addition to opening files consistently in UTF-8 without relying on the system encoding, I've also taken the liberty of adding a tox environment for python3.5 and a python 3.5 metadata classifier for PyPI.

### CODE REVIEW

**Comment by iliakur** [comment]
*Update*: found and fixed a tricky bug with file format checking that would have prevented users' specifications in `mongodb_fixtures` from taking effect!

**Comment by iliakur** [comment]
Hmm, it seems I've created a bit of a mess between Travis and Tox. Sorry about that. Let me know how you'd prefer that I proceed. Personally, I'm in favour of relying on Travis CI to provide different python versions and maybe just run `py.test` only, but maybe that change is too sweeping, so i could just revert my commits that have to do with this.

**Comment by mdomke** [comment]
Hej @Copper-Head! Thank you for your pull-request. I have made some good experiences with [tox-travis](https://github.com/ryanhiebert/tox-travis) when it comes to harmonize multiple Python versions and the Travis build matrix.
P.S.: Don't you think that it would be a good idea to add Python 3.6 support while we're at it?

**Comment by iliakur** [comment]
Ok, cool, I'd be up for trying out tox-travis!
Also, totally down for adding 3.6. Didn't want to bring it up until we solved the 3.5 issue :)
I'll update the PR in the next couple of days.

**Comment by iliakur** [comment]
Hurray, this worked :)

**Comment by mdomke** [comment]
Awesome! Thank you very much. I'll create a new release.

**Pull request merged**
